FROM maven:3.6-openjdk-17-slim

# Install libfreetype6
RUN apt-get update && apt-get install -y libfreetype6 && rm -rf /var/lib/apt/lists/*

WORKDIR /work
COPY pom.xml .
RUN mvn test clean --fail-never -DskipTests=true
COPY src src
