FROM maven:3.6-openjdk-17-slim AS build
RUN sed -i 's/deb.debian.org/archive.debian.org/g' /etc/apt/sources.list
RUN sed -i 's/stable\/updates/stable-security\/updates/' /etc/apt/sources.list
RUN sed -i '6 s/^/#/' /etc/apt/sources.list
RUN rm -f /etc/apt/sources.list.d/stretch-backports.list
RUN mkdir /work
WORKDIR /work
COPY pom.xml .
RUN mvn verify clean --fail-never -DskipTests=true
COPY src/main src/main
RUN mvn package -DskipTests=true

FROM maven:3.6-openjdk-17-slim
RUN sed -i 's/deb.debian.org/archive.debian.org/g' /etc/apt/sources.list
RUN sed -i 's/stable\/updates/stable-security\/updates/' /etc/apt/sources.list
RUN sed -i '6 s/^/#/' /etc/apt/sources.list
RUN rm -f /etc/apt/sources.list.d/stretch-backports.list
RUN apt-get update && apt-get install -y netcat && rm -rf /var/lib/apt/lists/*
RUN curl -L https://github.com/Droplr/aws-env/raw/master/bin/aws-env-linux-amd64 -o/usr/local/bin/aws-env && \
    chmod +x /usr/local/bin/aws-env && aws-env
COPY --from=build /work/target/highwire-1.0-SNAPSHOT.jar /usr/app/highwire.jar
CMD bash -c 'eval $(aws-env) && java -XX:InitialRAMPercentage=70.0 -XX:MaxRAMPercentage=70.0 -jar /usr/app/highwire.jar'
